# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: book.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\nbook.proto\x12\x11org.epam.grpctask\"\x19\n\x0b\x42ookRequest\x12\n\n\x02id\x18\x01 \x01(\x05\"8\n\x0c\x42ookResponse\x12\n\n\x02id\x18\x01 \x01(\x05\x12\x0c\n\x04name\x18\x02 \x01(\t\x12\x0e\n\x06\x61uthor\x18\x03 \x01(\t2Y\n\x0b\x42ookService\x12J\n\x07getBook\x12\x1e.org.epam.grpctask.BookRequest\x1a\x1f.org.epam.grpctask.BookResponseB\x02P\x01\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'book_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'P\001'
  _globals['_BOOKREQUEST']._serialized_start=33
  _globals['_BOOKREQUEST']._serialized_end=58
  _globals['_BOOKRESPONSE']._serialized_start=60
  _globals['_BOOKRESPONSE']._serialized_end=116
  _globals['_BOOKSERVICE']._serialized_start=118
  _globals['_BOOKSERVICE']._serialized_end=207
# @@protoc_insertion_point(module_scope)
